language: node_js
node_js:
  - "6"
  - "8"
script:
  - npm run lint
  - npm run test:unit:coverage:cc
  - npm run test:functional:ava
  - npm run test:functional:mocha
  - npm run test:functional:tap
